#!/bin/bash
# Fetch RCSB biological assembly 1 for every entry in data/campaign/pdb_entries.txt.
# The biological assembly, not the asymmetric unit: a crystal ASU contains lattice contacts that are not
# interfaces, and the real dimer is often generated by symmetry and absent from the ASU altogether.
# Assembly 1 is the author/software designated unit; entries with several assemblies contribute only their
# first, which is recorded as a known limitation rather than handled.
set -u
D="${ESM_PROAE_ROOT:?set ESM_PROAE_ROOT}/data/external/pdb_assemblies"
mkdir -p "$D"
LIST="${1:?usage: fetch_pdb_assemblies.sh <pdb_entries.txt>}"   # written by code/cm17_pdb_index.py
mkdir -p "$D/cif"
fetch_one() {
    p="$1"; out="$2/${p}.cif.gz"
    [ -s "$out" ] && return 0
    curl -sfL --retry 3 --retry-delay 2 --max-time 300 \
         "https://files.rcsb.org/download/${p}-assembly1.cif.gz" -o "$out.part" \
      && mv "$out.part" "$out" || { rm -f "$out.part"; echo "$p" >> "$2/../failed.txt"; }
}
export -f fetch_one
: > "$D/failed.txt"
tr -d '\r' < "$LIST" | xargs -P 12 -I{} bash -c 'fetch_one "$@"' _ {} "$D/cif"
echo "downloaded: $(ls "$D/cif" | wc -l) / $(wc -l < "$LIST")"
echo "failed:     $(wc -l < "$D/failed.txt")"
du -sh "$D/cif"
